### ISSUE TITLE
Crashes when lightning strikes a zombie horse

### ISSUE THREAD

**Issue by Terra777** [ChosenArchitect/ChosensModdedAdventure#124]
**Describe the bug**
->Not sure if it's reproducable but basically i randomly had an instant crash when a zombie horse got struck by a lightning. And for a brief moment I saw the monster spawn on top of the horse, but in that moment the game crashed. The issue occured in overworld.
**To Reproduce**
1. Zombie horse
2. make it be struck by lighting
3. Crash
4. Thats what happened

**Expected behavior**
-> Lighting > monster spawns and then fight 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
Unfortunately i don't have those kind of reflexes.

**Modpack version**
->0.9.0
**Java Version**
->no clue bro...it's whatever makes me run every modpack on this planet
**Modpack Launcher Used**
->
**Ram Allocated**
->10848MB to all my modpacks

**Additional context**
-> I am not certain but i do think that the horse might be spawned by apotheosis as a ride for one of their blue named bosses. As i did see before i went to sleep a monster there in that general area that was gone later. Also, horse was in the vicinity of another mob. I don't remember clearly but i think it was a chicken. But it might have been a different or modded mob.

Here's the crash log:
https://pastebin.com/hZqxSqcy

**Comment by 5ully** [comment]
I am unable to reproduce this with your steps.

**Comment by Terra777** [comment]
Unfortunate. All good then. Must be a one off or sth.
Thanks

**Comment by ChosenArchitect** [comment]
Seems to be the same issue as https://github.com/ChosenArchitect/ChosensModdedAdventure/issues/114 I need to see if I can find what the issue is? It might be something to do with Supplementaries. Ill work on updating everything this weekend! in the mean time if you want to run the latest update you can enable this. 

**To enable the error fixing Forge setting for 1.13 and newer, please follow these steps:**

- Navigate to your instance folder and click your world folder. In this example, my world is called my-forge-world.

- Within your world folder, click the folder called serverconfig.

- Find the file forge-server.toml and click Edit.

- Scroll down until you find the settings removeErroringEntities and removeErroringTileEntities which we've highlighted below.

- Change one or both of the settings from false to true as shown below as needed.

Then simply save the file and relaunch your modpack. When your pack starts, the new settings will take effect. When you next connect to your save and load the chunk with the ticking block entity, Forge will attempt to automatically remove the block that is causing issues.

Once the problem has been fixed, we recommend changing the settings back to false to prevent any issues with your world. But if recurring this can be a temp fix while an update is in progress.

**Comment by 5ully** [comment]
I looked further into this and #114 and it might be the mod Friends and Foe. Or another mod changing how entity ticks behave leading to false reports/unprecise crash logs.
