### ISSUE TITLE
Mod Sugestions

### ISSUE THREAD

**Issue by Aidenhart** [ChosenArchitect/ChosensModdedAdventure#2]
I suggest botania for the modpack because it is such a fun mod to use and mess around with

**Comment by ChosenArchitect** [comment]
It hasn't been updated to 1.20.1 yet and don't know if it will... I'll keep an eye on it! https://www.curseforge.com/minecraft/mc-mods/botania

**Comment by salehabdullah216** [comment]
updating project Architect once project e  updates

**Comment by Aidenhart** [comment]
Maybe add the Essential Mod By SparkUniverse 
The Mod makes multiplayer with friends much easier and adds emotes and cosmetics

**Comment by lays24mc** [comment]
How about "smarter villagers" e.g. if you want to build a village? There the mod would be good: https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant

Then to bypass the sieges, through the Villages: https://legacy.curseforge.com/minecraft/mc-mods/siege-stopper

I like to build cities or villages with Villagers, there are the two mods because very suitable for, I think :)

**Comment by CoralSkye** [comment]
May we add **Polymorph** for conflicting mod recopies?

**Comment by AlohaXChicken** [comment]
Add Mekanism please
