### ISSUE TITLE
Crafting table UI dosent show up

### ISSUE THREAD

**Issue by Bru-ba** [ChosenArchitect/ChosensModdedAdventure#37]
**Describe the bug**
I tried it in a few worlds, just to see if it had anything to do with it. When I interact with a "crafting table" or "crafting table on a stick", the UI doesn't show up and I'm unable to craft anything in my Inventory. Spamming the esc-key seems to close the invisible crafting table window.

**To Reproduce**
1. Craft a "crafting table"/"crafting table on a stick"
2. (Place it and) interact with it

**Expected behavior**
It should appear as if nothing happened. Trying to craft in the inventory does nothing.

**Modpack version**
Version 0.2.2

**Java Version**
Version 8 Update 381 (Build 1.8.0_381-b09)

**Modpack Launcher Used**
I use curseforge

**Ram Allocated**
10624mb

**Comment by MalaChaiLatte** [comment]
Try using java 17, that may help

**Comment by ChosenArchitect** [comment]
yea I am not sure what the issue is here as I can open the UI of the crafting table on a stick with no issues at all. make sure to be on the latest version of the modpack and use the Cruseforge launcher just to make sure you are downloading every mod as some launchers are having issues downloading the modpack correctly.
